project:
  type: website
  output-dir: docs
  post-render: encrypt_.r
  resources:
    - CNAME
    
website:
  title: "danynash"
  back-to-top-navigation: true
  sidebar: true
  google-analytics: "G-M437T2YZW3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about_me.qmd
      - myresearch.qmd
      - publications.qmd
      - tutorials.qmd
      - lessons.qmd
format:
  html:
    theme: Spacelab
    css: styles.css
    toc: true
    page-layout: full


editor: visual

