project:
  type: website
  output-dir: docs
  resources:
    - CNAME


website:
  title: "danynash"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - tutorials.qmd
      - listados.qmd
format:
  html:
    theme: Spacelab
    css: styles.css
    toc: true
    page-layout: full

editor: visual

