---
title: "What is learned in physics laboratories in higher education?"
description: "International literature review on what is learned in introductory physics laboratory courses"
date: "2022-06-28"
---

::: panel-tabset
## Español

# 1. Introducción

Una de las estrategias de enseñanza distintivas que se ha promovido desde hace décadas en el campo de la educación de la física la conforman los laboratorios de física (Hanif, Sneddon, Al-Ahmadi, & Reid, 2009; Kirkup et al., 1998). En efecto, los laboratorios de física han tenido durante mucho tiempo un papel crucial y central en el currículo con el fin de establecer y transferir a los estudiantes los logros de aprendizaje asociados a las habilidades que requiere un científico (Etkina et al., 2006; Derek Hodson, 1993; Avi Hofstein & Lunetta, 1982, 2004). Estas habilidades, conocidas como habilidades científicas, están fundamentalmente asociadas a los procedimientos, procesos y métodos que un científico usa cuando construye conocimiento y resuelve problemas experimentales (Etkina et al., 2006) y, serían promovidas de manera significativa en los laboratorios de física. Así pues, se entenderá a los laboratorios de física como una forma de actividad práctica, definida esta última como aquellas experiencias de aprendizaje en las cuales los estudiantes interactúan con materiales y/o modelos para observar y comprender el mundo natural (Avi Hofstein & Lunetta, 2004).

Ahora bien, la presencia de los laboratorios de física en carreras asociadas al área STEM (Science Technology Engineer and Mathematics) ha jugado un papel crucial en la promoción de las habilidades científicas que se requieren en la era actual (Singer, Hilton, & Schweingruber, 2006). Según el reporte de la American Association of Physics Teachers (AAPT), el laboratorio de pregrado representa una parte esencial en el plan de estudios de física debido al carácter inherentemente experimental que tiene la física (Kozminski et al., 2014). De esta manera, la AAPT releva la creciente conciencia de los laboratorios en la instrucción de un conocimiento profundo de la física. Sin embargo, a pesar de relevar la importancia que tendrían los laboratorios de física, todavía no existen evidencias claras con respecto al efecto que tendrían en el aprendizaje de los estudiantes. Ciertamente, si bien, diferentes estudios coinciden en que el aprendizaje basado en la experimentación ha tenido un rol central en la educación de las ciencias, y en especial en la física (A Hofstein & Mamlok-Naaman, 2007; Avi Hofstein & Lunetta, 1982; Natasha G. Holmes & Wieman, 2018) opiniones divergentes se observan en la literatura en relación con el impacto que tendrían los laboratorios de física en el aprendizaje.

Por un lado, Tobin (1990) argumenta que las actividades que se realizan en los laboratorios permitirían a los estudiantes aprender y, al mismo tiempo, participar en los procesos de construcción de conocimiento haciendo ciencia. De manera similar, Deters (2005) descubrió que los laboratorios de físicas estimularían y motivarían a los estudiantes a aprender más sobre ciencia. Además, existe evidencia en cuanto a que el compromiso de los estudiantes tiene un impacto positivo en los logros en física y que estarían mediadas por estas actividades (Lee, Lai, Yu, & Lin, 2012). Bajo la misma línea, los laboratorios de física representan un rico espacio de aprendizaje donde se produce investigación científica auténtica (Hume & Coll, 2008). De esta manera, se ha evidenciado que los laboratorios de física entregarían a los estudiantes oportunidades para aumentar sus capacidades tales como el pensamiento crítico, habilidades orales y escritas, trabajo colaborativo y responsabilidad, entre otras (Hanif et al., 2009).

Por otro lado, recientes investigaciones sugieren que ayudar a los estudiantes a lograr los resultados de aprendizaje deseados mediante actividades de laboratorio es un proceso altamente complejo (Avi Hofstein & Lunetta, 2004), en conjunto con los altos costos monetarios y de tiempo que implica enseñar en estos contextos (Natasha G. Holmes & Wieman, 2018). Dentro de las razones de estas críticas, se encuentra el cuestionable aporte que entregarían algunas actividades dentro de los laboratorios debido a la implementación de experimentos en forma de "recetas de cocina". Estas actividades dificultarían la capacidad de razonamiento del estudiante como la oportunidad de que adquieran múltiples habilidades involucradas en la investigación científica (Bless, 1933). Ahora bien, desde la práctica instruccional, también se han observado críticas. Desde luego, entre las dificultades que se observan, destacan: (i) la confusión entre el rol del científico y el rol del estudiante en las ciencias; (ii) la confusión entre la psicología del aprendizaje y la filosofía que sustenta a la ciencia (Flores, Caballero Sahelices, & Moreira, 2009; D Hodson, 1994); y, (iii) el hecho de que cada tipo de experiencia o actividad dentro del laboratorio tiene diferentes procesos de enseñanza y, por lo tanto, cada una de estas actividades debe ser evaluada en base a dichas limitaciones (Gülçiçek, Kizilcik, & Damli, 2018). Finalmente, también se ha visto que, cuando llegan a las actividades de laboratorios, los estudiantes generalmente no tendrían claridad acerca de las técnicas y las habilidades necesarias para realizar un particular experimento, dando cuenta de una baja comprensión que tendrían los estudiantes acerca de los principios científicos subyacentes a cada actividad de laboratorio (Croker, Andersson, Lush, Prince, & Gomez, 2010).

Debido al bajo acuerdo que tiene la comunidad sobre el efecto de los laboratorios de física en los procesos de aprendizaje de los estudiantes, nuevas formas de laboratorios -denominados laboratorios no-tradicionales- emergieron como alternativa para lograr transferir los logros de aprendizaje en los estudiantes. De manera específica, estas formas no-tradicionales de laboratorio tendrían como principales objetivos: (i) promover efectos positivos en la enseñanza conceptual de la física; (ii) otorgar mayores oportunidades de aprendizaje a los estudiantes; (iii) promover diversas habilidades científicas que se encuentran el currículo actual (OECD, 2017). Así, entre los laboratorios no tradicionales que más destacan se encuentran las simulaciones virtuales, laboratorios online, interacción con datos extraídos de la vida, entre otros (Singer et al., 2006). No obstante, a pesar de que estas formas de laboratorios no-tradicionales han logrado alinearse con los objetivos de aprendizaje que se establecen en el currículo de la física, aún no existe evidencia contundente sobre los efectos que tendrían en la promoción de habilidades científicas (Teachers, 2014). En la misma línea, poca claridad existe en cuanto a los objetivos de aprendizaje que deben abarcar los cursos de laboratorios tradicionales y no-tradicionales (Avi Hofstein & Lunetta, 1982, 2004; Kozminski et al., 2014). Según lo recomendado por la AAPT, los logros de aprendizaje que darían cuenta de las dimensiones para el desarrollo de un currículo de laboratorio de física serían: (i) analizar y visualizar datos; y (ii) comunicar; (iii) construir conocimiento; (iv) desarrollar habilidades técnicas y prácticas de laboratorio; (v) diseñar experimentos; (vi) modelar. Sin embargo, los logros de aprendizaje entregados por la AAPT solamente representan recomendaciones y, por tanto, su alineación con el currículo estaría sujeta a discusión. Lo anterior, dificulta la práctica pedagógica y las estrategias de evaluación utilizadas para medir los efectos que tienen los laboratorios en los logros de aprendizaje de los estudiantes.

En síntesis, se releva el rol de los laboratorios de física como una forma de descubrimiento científico, que requiere la observación personal y la experimentación a través de las prácticas científicas. Sin embargo, existe bajo acuerdo sobre el efecto de los laboratorios de física en la promoción de aquellos conocimientos y habilidades que se relacionan con la práctica científica y, que requieren ser promovidas en los estudiantes para la formación de científicos íntegros y capaces de resolver los problemas complejos en la época actual. Dicho lo anterior, resulta necesario conocer y entender qué es lo que aprenden los estudiantes en los laboratorios de física de pregrado. Para responder a esta necesidad, se propone una revisión sistemática de la literatura en torno a la pregunta ¿Qué aprenden los estudiantes en los laboratorios de física en la Educación Superior?

Para responder a la pregunta de revisión, este estudio se focaliza en estudiantes de pregrado que asisten a cursos de laboratorios de física o, de manera equivalente, aquellas carreras del área STEM. En términos generales, esta revisión entrega un análisis crítico sobre lo que aprenden los estudiantes en los laboratorios de física con foco en tres grandes dimensiones: (i) la dimensión habilidad, que da cuenta de las habilidades experimentales, análisis de datos y de comunicación que aprenderían los estudiantes, relevando el rol de la comunicación como una habilidad esencial del científico; (ii) la dimensión conocimiento, que entrega luces sobre el conocimiento disciplinar que aprenden los estudiantes a través de los laboratorios; y, (iii) la dimensión actitudinal, que guarda relación con aquellos elementos psico-emocionales que aprenden los estudiantes en estos contextos. De esta manera, los resultados de esta revisión permitirán: (i) informar sobre los logros de aprendizaje de los estudiantes de manera tal de alinear el currículo de física (ii) ayudar a la implementación de actividades de laboratorios que promuevan aquellas habilidades científicas esenciales; y, (iii) entregar señales acerca de las estrategias de evaluación que se utilizan para dar cuenta de los logros de aprendizaje de los estudiantes.

# 2. Metodología

El propósito de esta revisión de literatura es examinar estudios empíricos que aborden lo que se aprende en los laboratorios de física en cursos de educación superior. Para ello, se realizó una búsqueda de artículos empíricos publicados entre los años 2010 y 2018 en la base de datos Web of Science (WOS). En primer lugar, con el objetivo de eliminar todo artículo que no refería exclusivamente a los laboratorios de física, se realizó un primer filtro en el título. Para ello, se utilizó lab\* como palabra clave para incluir todas las variantes de la palabra laboratorio. Se justifica el filtro anterior por razones prácticas, ya que, en caso de no realizar este filtro a nivel de título, la lista de resultados crece superando los 2000 artículos. Sin embargo, debe consignarse que este filtro podría sesgar los resultados. En segundo lugar, se realizó un segundo filtro a nivel de títulos, abstracts o palabras clave de los artículos empíricos que lograron pasar el primer filtro. Luego, la palabra clave que se utilizó en este caso fue physic\$, incluyendo así, artículos que refieren al área de física. De manera similar, se utilizaron las palabras claves biology\* y chem\* para excluir aquellos artículos que no refieran exclusivamente al área de física. También, se utilizaron las palabras advanc\* NEAR/1 lab*, online*, simulat\* y virtual\* para excluir artículos que referían a laboratorios avanzados, online, simulados o virtuales. Adicionalmente, se utilizó secondary\* como última palabra clave para excluir todos los artículos que referían a un nivel escolar secundario. De esta manera, se obtuvieron 120 artículos -- no hubo filtro a nivel de áreas disciplinares y/o revistas-, de los cuales se excluyó inicialmente un artículo por estar dos veces en la lista. Posteriormente, se revisaron los resúmenes, introducción, metodología y resultados de los artículos, a partir de los cuales se eliminaron 79 artículos distribuidos en cinco grupos. El primer grupo de artículos eliminados, compuesto por 51, lo conforman aquellos artículos que no presentaba evidencia de alguna intervención con estudiantes. El segundo grupo eliminado, 5 en total, abordaban aspectos teóricos principalmente. El tercer grupo eliminado, compuesto por 10 artículos, se enfocaba en estudiantes pre-universitarios o graduados de la universidad. El cuarto grupo de artículos eliminados, 9 en total, estaban escritos en idiomas diferentes al español o inglés. El último grupo de artículos eliminados estaban relacionados con libros o handbooks, de aquí excluyeron 2 artículos.

# 3. Resultados

En la @tbl-table1 se encuentra un resumen de los resultados que emergieron de los estudios empíricos y, que respondería de manera explícita a la pregunta sobre lo que aprenden los estudiantes en los laboratorios de física. Tal como se muestra en la tabla I, se identificaron cuatro dimensiones que reflejan los patrones comunes en relación con lo que aprenden los estudiantes en los cursos de laboratorio, estos son: (i) Habilidades; (ii) Conocimiento; (iii) Actitudes. En primer lugar, la dimensión habilidades, abordada ampliamente por 35 artículos empíricos, refiere a los procesos cognitivos que se promueven, ya sea de manera directa o indirecta mediante la actividad de laboratorio. Esta dimensión se subdividirá en (a) análisis de errores y manejo de incertidumbre, abordado por 4 artículos; (b) uso de equipamiento instrumental, abordado por 7 artículos; (c) recolección, análisis y visualización de datos, que incluye 12 artículos; y, (d) comunicación, abordado por 10 artículos. En segundo lugar, 10 artículos incluyen la dimensión conocimiento dentro de las actividades de laboratorio para promover todo conocimiento tanto disciplinar como procedimental que se enseña en los contextos de laboratorio. En esta revisión, se considera de manera diferente aquellos conocimientos conceptuales, que solo refieren al entendimiento de conceptos abstractos de la física, de los conocimientos experimentales. De esta manera, emergen dos sub-dimensiones: (a) Comprender conceptos físicos; y, (b) Conectar conocimiento previo con experimentos. En tercer lugar, los aspectos actitudinales, definidos como un conjunto de actitudes que se promueven dentro de estos espacios, se abordan en 15 artículos. Así, a partir de esta dimensión emergen sub-dimensiones: (a) expectativas experimentales; y, (b) trabajo colaborativo.



| Dimensión                                                                            | Dimensión	Sub-dimensión |    Artículos              |
|----------------------|----------------------|--------------------------------------------------|
|Habilidades| Análisis de errores e incertidumbre |  (Day et al., 2016); (Sarasola et al., 2015); (Bergin et al., 2018);  (Kontro et al., 2018)|
|           |  Uso de equipamiento experimental |  (Holmes & Wieman, 2016); (Shi et al., 2015); (Huntula et al., 2011); (Leung et al., 2017); (Bouquet et al., 2017); (Shi et al., 2016); (Bergin et al., 2018); (Liu & Turkey, 2017); (Douglas et al., 2017)|
|            | Análisis de errores e incertidumbre |  (Day et al., 2016); (Sarasola et al., 2015); (Bergin et al., 2018);  (Kontro et al., 2018)|
|            |  Recolección, análisis y visualización de datos |  (Wieman & Holmes, 2015); (Wilcox & Lewandowski, 2017a); (Holmes & Wieman, 2016); (Kukliansky & Eshach, 2014); (Gandhi et al., 2016); (Day et al., 2016); (Bouquet et al., 2017); (Nixon, et. al, 2016); (Sarasola et al., 2015); (Kontro et al., 2018); (Parappilly et al., 2018); (Thomas & Meldrum, 2018); (Douglas et al., 2017)|
|            | Comunicación | (Beichner et al., 2010);  (Wilcox & Lewandowski, 2017a); (Holmes & Wieman, 2016); (Sharma et al., 2014); (Shi et al., 2015); (Donovan, 2014); (Ellingsen & Stovneng, 2018); (Thomas & Meldrum, 2018); (Douglas et al., 2017); (Stanley, Su, & Lewandowski, 2017)|
|Conocimiento| Conceptos físicos  |  (Wieman & Holmes, 2015); (Wilcox & Lewandowski, 2017a); (N. G. Holmes, et. al., 2017); (Güven et al., 2014); (Shi et al., 2016); (Kanim & Subero, 2010); (Thomas & Meldrum, 2018); (Sobhanzadeh et al., 2017), (Sarasola et al., 2015); (Douglas et al., 2017)|
|            | Conectar conocimiento previo con experimentos |  (Güven et al., 2014); (Huntula et al., 2011); (Leung et al., 2017); (Nixon, et. al, 2016); (Thomas & Meldrum, 2018); (Liu & Turkey, 2017); (Sobhanzadeh et al., 2017)|
|Actitudinales | Expectativas experimentales |  (Güven et al., 2014); (Wilcox & Lewandowski, 2017b); (Ayvaci, Yildiz, & Bakirci, 2015)|
|              | Trabajo colaborativo|   (Beichner et al., 2010): (Sharma et al., 2014); (Güven et al., 2014); (Leung et al., 2017); (Braun & Kirkup, 2015); (Mellingsæter, 2014); (Douglas et al., 2017); (Dounas-Frazer et al., 2017); (Stanley & Lewandowski, 2016b); (Liu & Turkey, 2017)|
: Dimensiones asociada  a lo que se aprende en los laboratorios de física {#tbl-table1}



### 3.1	Dimensión habilidades
#### 3.1.1	Análisis de errores e incertidumbre

La habilidad de análisis de errores e incertidumbre da cuenta del manejo estadístico con respecto al dominio de las incertezas que deben tener en cuenta los estudiantes durante la medición experimental. Esta es la habilidad que se promueve con menor frecuencia en los 41 estudios revisados. En cuanto a los resultados que emergen para esta categoría, todos los artículos reportan observar una ganancia en los logros de aprendizaje asociados a esta habilidad. Desafortunadamente, solo un artículo proporciona suficiente evidencia que valide dichos efectos, pues plantea un diseño que introduce de manera explícita la habilidad de manejo de errores e incertidumbre en su diseño de laboratorio, (Sarasola et al., 2015). De este modo, la escasa evidencia que se observa en la ganancia de logros de aprendizaje en torno a esta habilidad tendría relación con los objetivos definidos en el diseño previo de las actividades de laboratorio implementadas, que no lo incorporan de manera explícita (Bergin et al., 2018; Day et al., 2016; Kontro et al., 2018).

De manera específica, el estudio de Sarasola et al. (2015), releva el rol que tienen los laboratorios open-lab para evaluar los procesos de aprendizaje asociados a esta habilidad. De esta manera, mediante un enfoque cuantitativo, a través de la aplicación de un test pre-post y de rúbricas a reportes de laboratorios, observaron una ganancia con respecto al manejo de errores e incertidumbres. De manera contraria, la investigación de Kontro et al., (2018), a pesar de implementar el mismo tipo de laboratorio y el uso de rubricas de evaluación, no detalla de manera explícita el efecto que tendrían las actividades de laboratorio en la promoción de esta habilidad. Ahora bien, mediante la implementación de un laboratorio tradicional, las diferencias en la ganancia de logros de aprendizaje declarada en el estudio de Day et al. (2016), emerge desde una evaluación centrada en un cuestionario que no se centra exclusivamente en la promoción de habilidades asociadas a los errores e incertidumbre y, que tiene como objetivo central, analizar si existen diferencias en la ganancia de habilidades con respecto al género de los estudiantes. Finalmente, mediante un aprendizaje cooperativo basado en problemas, el estudio de Bergin et al. (2018) sustenta haber observado una ganancia positiva en la adquisición de esta habilidad mediante la aplicación de un cuestionario de percepciones, lo cual, no daría suficientes garantías concluyentes en torno a la significativa promoción de esta habilidad.  

#### 3.1.2	Uso de equipamiento experimental

El uso de equipos experimentales representa un aspecto crucial en las actividades de laboratorio y refiere a las habilidades asociadas a la construcción y testeo de equipamiento experimental, incluyendo la toma de mediciones con cuidado, comprensión de las técnicas y funcionamiento de instrumentos experimentales, Ahora bien, los resultados que emergen de esta revisión dan cuenta de que la promoción de las habilidades asociada al uso de equipamiento experimental no es clara. En primer lugar, tres artículos declaran observar efectos positivos con algunas dificultades asociadas, por un lado, a los tiempos que se requieren para la implementación de las actividades de laboratorios (Holmes & Wieman, 2016) y, por otro lado, a los instrumentos con los cuales se evalúan los logros de aprendizaje (Kontro et al., 2018; Shi et al., 2015). En segundo lugar, mediante reflexiones de los estudiantes, dos artículos observan efectos positivos en torno al entendimiento de los procesos científicos y a la importancia de los procedimientos experimentales (Huntula et al., 2011; Bergin et al., 2018). Finalmente, un artículo no observa ni efectos positivos ni negativos en torno a esta habilidad (Leung et al., 2017).

En cuanto a los efectos positivos, a pesar de que los estudios de Holmes & Wieman (2016),  Kontro et al., (2018) y Shi et al. (2015) observan una ganancia en habilidades asociada al testeo y uso de equipamiento experimental, el primero da cuenta que existen diversas dificultades para su promoción, quienes enfatizan que el tiempo destinado a promover esta habilidad debe ser planificado. En cuanto al segundo estudio mencionado, no detalla índices de validez en sus instrumentos de evaluación que garanticen los efectos positivos observados. Finalmente, los resultados expuestos por el estudio Shi et al. (2015), dan cuenta que los teléfonos inteligentes representan una herramienta útil para promover el uso de equipamiento experimental de bajo costo en los laboratorios de física, sin embargo, sus resultados se sustentan en un cuestionario de autoevaluación subjetiva de los estudiantes, lo que cuestiona la validez en los resultados.

Con respecto a las evidencias levantadas a partir de las reflexiones de los estudiantes, los estudios realizados por Huntula et al. (2011) y Bergin et al. (2018), coinciden en sus resultados. En efecto, a partir de las reflexiones de los estudiantes, se observa que estos entienden la importancia de los procedimientos experimentales teniendo mejor entendimiento de los procesos científicos subyacentes a la práctica científica.

Finalmente, el estudio realizado por el grupo Leung et al., (2017), no observa un efecto positivo ni negativo en la promoción de habilidades asociada al equipamiento experimental debido a que el estudio corresponde a una implementación de un nuevo proceso de evaluación que no se focalizaría específicamente en evaluar la promoción de esta habilidad. Además, los resultados obtenidos a partir las evaluaciones implementadas estarían fuertemente sesgadas debido a que solo fueron contestadas por uno de los integrantes de cada grupo que participó en las actividades de laboratorio.

#### 3.1.3	Recolección, análisis y visualización de datos

La habilidad de recolección, análisis y visualización de datos una de las habilidades que mayormente se enseña en los estudios analizados. Esta habilidad está asociada con la recopilación y extrapolación datos experimentales; el desarrollo de métodos estadísticos y gráficos para su evaluación; la utilización de EXCEL u otro software para trazar y luego ejecutar una regresión sobre datos; representar datos gráficamente. Así, por ejemplo, se comentan algunas de las actividades que mayoritariamente deben realizar las estudiantes asociadas a esta habilidad: manejo de datos (Holmes, et. al., 2017), análisis de gráficos de log-log (Wieman & Holmes, 2015), creación, entendimiento e interpretación de gráficos (Kukliansky & Eshach, 2014) y ajustes lineales (Day et al., 2016; Nixon, et. al, 2016; Kontro et al., 2018). Ahora bien, se observan resultados divergentes en relación con el efecto que tendrían las actividades de laboratorio en la promoción de esta habilidad.

Por un lado, y en mayor proporción, se tienen estudios que reportan observar ganancias positivas en la promoción de esta habilidad. Así, un grupo de estudios, mediante evaluaciones cuantitativas, observa ganancia en la implementación de actividades innovadoras, como lo son actividades basadas en juegos de LEGO (Parappilly et al., 2018), actividades andamiadas en diversas semanas (Gandhi et al., 2016), o, centradas en la indagación (Wilcox & Lewandowski, 2017a).  Otro grupo de estudios, observa ganancias en laboratorios tradicionales a través de las percepciones de los estudiantes respecto de la física (Bouquet et al., 2017) o mediante la aplicación de la aplicación de un test pre-post que evalúa habilidades de análisis y visualización de datos (Wieman & Holmes, 2015).

Por otro lado, solo dos estudios reportan resultados opuestos. En efecto, el estudio de Sarasola et al. (2015), observa que, mediante una modalidad open-ended, la introducción simultánea de la metodología experimental y el análisis de datos resulta ser confusa para los estudiantes, lo que dificultaría un aprendizaje significativo. En la misma línea, Kukliansky & Eshach (2014) observaron que los aspectos más desafiantes para los estudiantes es la construcción de gráficos en papel en diversas escalas, quienes concluyen que para promover un aprendizaje significativo en estudiantes de primer año se debe considerar tanto el conocimiento conceptual como el procedimental.

#### 3.1.4	Comunicación

Esta habilidad comprende competencias transversales y propias de la disciplina de la física, entendida como aquella habilidad, mediante la cual los estudiantes expresan sus observaciones experimentales, sus resultados y argumentan de manera ordenada usando las evidencias experimentales. A partir de los estudios analizados, emergen dos dimensiones que expresan las distintas formas de comunicación que se da en los laboratorios de física, estas son, la comunicación escrita (Donovan, 2014; Sharma et al., 2014; Stanley & Lewandowski, 2016b; Stanley, Su, & Lewandowski, 2017; Kontro et al., 2018) y la comunicación oral (Douglas et al., 2017; Wilcox & Lewandowski, 2017a). 

Dentro de las habilidades de comunicación escrita, destacan artículos que se centran en la presentación de resultados experimentales mediante reportes de laboratorio (Donovan, 2014; Sharma et al., 2014; Stanley & Lewandowski, 2016b; Stanley, Su, & Lewandowski, 2017), cuadernos de laboratorio (Donovan, 2014), o en formato poster (Kontro et al., 2018). Por otro lado, dentro de las habilidades de comunicación oral, destacan los reportes en formato video (Douglas et al., 2017) o comunicación oral en formato de presentaciones (Wilcox & Lewandowski, 2017a). Sin embargo, ninguno de estos artículos, ya sea los que promueven actividades de comunicación escrita u oral, utilizan los registros de comunicación de los estudiantes para dar cuenta de las dificultades y/ ganancia en el aprendizaje. Por lo tanto, sería apresurado afirmar algún efecto significativo en relación con la promoción de habilidades de comunicación en los laboratorios de física. Así se evidencia, por ejemplo, en el estudio de Stanley & Lewandowski (2016b), en el que luego de consultar a estudiantes graduados por el beneficio que tendrían los cuadernos de laboratorios, emergieron inquietudes e incertidumbres en el impacto que tendrían estos en el aprendizaje.

### 3.2 Dimensión Conocimiento

En cuanto a los conocimientos que se aprenden en los laboratorios de física, estos referirían mayormente a un conocimiento conceptual y/o experimental y aquellos que lo conectan con experiencias del mundo-real. Además, estos conocimientos varían según carrera y año disciplinar. Así, los conocimientos conceptuales que mayormente se abordan en los artículos analizados, 13 en total, lo comprenden aquellos relacionados con mecánica de Newton (Kanim & Subero, 2010; Wieman & Holmes, 2015; Shi et al., 2016; Holmes, et. al., 2017; Sobhanzadeh et al., 2017; Leung et al., 2017; Nixon, et. al, 2016; Thomas & Meldrum, 2018; Liu & Turkey, 2017; Douglas et al., 2017), electricidad y magnetismo (Güven et al., 2014; Wieman & Holmes, 2015) o aplicación de conocimiento matemático (Sarasola et al., 2015). Estos conocimientos serían los conceptos físicos que mayormente se abordan en los cursos introductorios de física, es decir, en los dos primeros años de carrera universitaria.  En cuanto a conocimiento conectado con experiencias del mundo real, resalta aquella que da cuenta de las experiencias previas de los estudiantes con experimentos o actividades de laboratorios (Huntula et al., 2011; Güven et al., 2014; Sobhanzadeh et al., 2017; Thomas & Meldrum, 2018).

Por un lado, en cuanto al efecto en la promoción de conocimiento conceptual, solo cuatro artículos, declaran haber observado un efecto positivo en mecánica y/o electricidad y magnetismo durante las actividades de laboratorios de física (Kanim & Subero, 2010, Shi et al., 2016; Sobhanzadeh et al., 2017; Douglas et al., 2017). No obstante, debe consignarse que, si bien, estos estudios declaran observar efectos en la ganancia de conocimiento, tales efectos no se disociarían de aquellas habilidades experimentales y, por lo tanto, las ganancias de conocimiento conceptual en mecánica y/o electricidad y magnetismo reportadas por estos cuatro artículos, no entregaría suficiente evidencia para demostrar un aprendizaje en conocimiento mediante los laboratorios de física. 

Finalmente, lo que mayormente destaca en los artículos analizados en cuanto a la promoción de conocimiento conceptual, es la conexión de conocimiento previo con experimentos o actividades de laboratorio. Así, uno de los principales aprendizajes que tendrían los estudiantes, medido mediante pruebas cuantitativas, sería el entendimiento de los conceptos conectándolos con la observación, experiencia de la vida real y experiencias previas (Huntula et al., 2011; Güven et al., 2014; Sobhanzadeh et al., 2017; Thomas & Meldrum, 2018).   

### 3.3 Dimensión Actitudinal

Para esta dimensión, un tipo de actitud que emerge como principal es la de trabajo colaborativo, abordada por 10 artículos.  En particular, para esta sub-dimensión se observan dos conjuntos de resultados. El primer conjunto, engloba la capacidad que tendrían los estudiantes para trabajar de manera colaborativa tanto con sus pares (Beichner et al., 2010; Mellingsæter, 2014; Sharma et al., 2014; Douglas et al., 2017; Dounas-Frazer et al., 2017; Leung et al., 2017) y con profesores (Braun & Kirkup, 2015). El segundo conjunto, refiere a la capacidad que tienen los estudiantes para trabajar colaborativamente en actividades de documentación (Stanley & Lewandowski, 2016b; Liu & Turkey, 2017).  Otro aspecto que da cuenta de la dimensión actitudinal, refiere a las expectativas de los estudiantes acerca de la experimentación en la física, abordada por 3 artículos (Güven et al., 2014; Ayvaci, Yildiz, & Bakirci, 2015; Wilcox & Lewandowski, 2017b).

En cuanto al primer conjunto de resultados de la sub-dimensión trabajo colaborativo, se observa que los estudiantes valorarían positivamente el trabajo colaborativo, siendo una práctica habitual fuera y dentro de los contextos de laboratorio (Sharma et al., 2014). Además, se observaron ganancias en las habilidades para colaborar en grupo mediante actividades centrada en el trabajo de pares (Leung et al., 2017; Sharma et al., 2014). Ahora bien, en cuanto al segundo conjunto se observa que aquellas actividades que promueven sistemáticamente la actividad de documentación centrada en trabajo de pares, involucran un proceso de mayor complejidad debido a que representan tareas propias de la investigación científica y, por tanto, tienen asociadas habilidades de orden superior (Liu & Turkey, 2017; Stanley & Lewandowski, 2016b). Complementando lo anterior, el trabajo desarrollado por Stanley & Lewandowski, (2016b) propone que el diseño de las actividades de laboratorio juega un aspecto crucial para definir futuras implementaciones de actividades que permitan a los estudiantes adquirir efectivamente aquellas actitudes asociadas a la documentación científica mediante el trabajo colaborativo. 

Finalmente, en relación con las expectativas experimentales, emergen estudios centrados en el entendimiento de la naturaleza de los experimentos que tienen los estudiantes de carreras científicas (Wilcox & Lewandowski, 2017b) y, estudiantes de carreras de pedagogía (Güven et al., 2014; Ayvaci, Yildiz, & Bakirci, 2015). En cuanto a las expectativas de estudiantes de carreras científicas, el estudio longitudinal realizado por Wilcox & Lewandowski (2017b), da cuenta, mediante la aplicación de un cuestionario de percepción, que existe un aumento en las expectativas de los estudiantes. Sin embargo, este efecto no sería impulsado por los laboratorios, sino que por la selección de estos estudiantes que tendrían expectativas mayormente alineadas con las de un experto. Ahora bien, en cuanto a las expectativas de estudiantes de carreras de pedagogía, los estudios de Ayvaci, Yildiz, & Bakirci (2015) y Güven et al (2014) exploran las reflexiones experimentales en cursos de laboratorio innovadores y open-ended, respectivamente. Así, se demuestra que la instrucción realizada con materiales que se imprimen en laboratorio basados en el modelo 5E, mejoró los logros académicos de los futuros maestros en comparación con profesores que asistieron a laboratorios tradicionales (Ayvaci, Yildiz, & Bakirci, 2015). Por otro lado, resultados que emergen del estudio de Güven et al. (2014), revelan que las creencias epistemológicas de los profesores en formación se desarrollarían en relación con la capacidad innata de estos, su fuente de conocimiento, el aprendizaje rápido y las dimensiones del conocimiento simple.

# 4. Discusión y conclusión

Este estudio ha revisado 41 estudios relacionado con los aprendizajes de los estudiantes los laboratorios de física de pregrado. Los datos presentes en este cuerpo de la literatura empírica sugieren que la promoción de logros de aprendizaje de habilidades científicas sigue siendo un tema en la cual no existe un consenso claro y definido. Por un lado, los logros de aprendizaje que menor consenso tienen son aquellos que refieren a la habilidad de analizar errores, usar equipamiento experimental, recolección y análisis de datos y, a la actitud expectativas experimentales de los estudiantes. Por otro lado, los logros de aprendizaje que presentan mayor consenso en los estudios empíricos estudiados están relacionados con las habilidades de comunicación, los conocimientos abstractos y experimentales y, la actitud trabajo colaborativo.

En cuanto al conjunto de resultados que presentan mayor disenso en torno a lo que aprenden los estudiantes en los laboratorios de física, se debería principalmente, a lo complejo que resulta aislar las habilidades o actitudes en cada actividad de laboratorio (Etkina, Ruibal-villasenor, Jordan, & Hmelo-silver, 2014; AAPT, 2014). Lo anterior, pareciera reflejarse en los diseños que se establecen en los laboratorios de física, en la cual no se explicitan todos los objetivos de aprendizajes que, luego, son evaluados y reportados. Por ejemplo, en relación con la promoción de habilidades de análisis de errores, tres de los cuatros artículos que declaran observar alguna ganancia en dicha habilidad, no lo define previamente en sus actividades de laboratorio (Day et al., 2016; Bergin et al., 2018; Kontro et al., 2018). En una línea similar, en cuanto a la ganancia de uso de equipamiento experimental, se releva la constante tensión en relación con los tiempos destinados a la implementación de una actividad o con los instrumentos de evaluación que se utilizan para dar cuenta de alguna ganancia, lo cual cuestiona si se cumplen los criterios de validez en dichos estudios (Shi et al., 2015, Leung et al., 2017; Kontro et al., 2018). Análogamente, a pesar de que la promoción de habilidades asociada al análisis de datos es ampliamente abordada por los estudios empíricos analizados, existe fuerte disenso respecto de esta habilidad. Mayormente, por el tipo de laboratorio que se implementa: opend-ended (Sarasola et al., 2015), basado en la indagación (Wilcox & Lewandowski, 2017a), andamiadas semanalmente (Gandhi et al., 2016), o basadas en actividades con LEGO (Parappilly et al., 2018), o bien, por la variedad y complejidad de los tópicos que abarcan esta habilidad, y que difícilmente se capturan a través de cuestionarios (Kukliansky & Eshach, 2014). Con respecto a lo anterior, se hace relevante que los logros de aprendizaje se midan con instrumentos adecuados y alineados al curriculum o al diseño de cada actividad de laboratorio.

Ahora bien, se observa una situación particular con la promoción de habilidades de comunicación, cuyo interés ha crecido rápidamente sobre todo en el estudio de las conversaciones (Douglas et al., 2017; Wilcox & Lewandowski, 2017a) y en argumentación de los estudiantes (Donovan, 2014; Sharma et al., 2014; Stanley & Lewandowski, 2016b; Stanley, Su, & Lewandowski, 2017). Sin embargo, todos los estudios que abordan esta dimensión no declaran precisamente observar una ganancia en torno a las habilidades de comunicación, o en torno a una mejora del uso del lenguaje o en la adquisición de habilidades lingüísticas propiamente tal, sino más bien, estas habilidades de comunicación darían cuenta de la ganancia de otras habilidades. En ese sentido, existe una suerte de conciencia colectiva que daría cuenta, sin evidencia empírica sustancial, que la ganancia de logros de aprendizaje se cristaliza en los escritos o discursos de los estudiantes. Como consecuencia, es necesario tensionar el rol que tienen la comunicación en cada actividad de laboratorio, en los instrumentos de evaluación que están mediados por este componente y en los efectos que tendría esta habilidad en las otras habilidades científicas. Dicho lo anterior, el análisis de los artículos releva la necesidad de investigaciones que ahonden en esta problemática de manera tal de dilucidar qué tanto median las habilidades de comunicación en los procesos de aprendizaje de los estudiantes.

Aun cuando los resultados que emergen de esta revisión cuestionan el efecto que tendrían los laboratorios de física en el aprendizaje de los estudiantes, fundamentalmente debido a la falta de evidencia empírica, a la superposición de las habilidades científicas lo que complejiza su alineamiento curricular y a la diversas implementaciones de laboratorios de física (por ejemplo opend-ended, basado en la indagación, basado en juegos de LEGO, tradicional, no tradicional, etc.), existen algunas luces claras en cuanto a la promoción de logros asociados a conocimientos abstractos y experimentales, y a aspectos actitudinales (Beichner et al., 2010; Mellingsæter, 2014; Sharma et al., 2014; Douglas et al., 2017; Dounas-Frazer et al., 2017). Por un lado, se observan resultados positivos en cuanto a la ganancia de conocimientos, que varían de acuerdo al año y carrera del estudiante. No obstante, estos resultados no serían del todo novedosos debido al uso sustantivo de test que dan cuenta de alguna ganancia de conocimientos pero que estarían mediados por conocimientos previos, o bien aquellos que se aprenden en las cátedras teóricas. Por otro lado, en cuanto a aspectos actitudinales, su ganancia se sustenta mayormente a través de las percepciones de los estudiantes, quienes reportan efectos positivos. Desde esta perspectiva, parece ser que la comunidad científico-educativa pone mayor énfasis en promover dichos aprendizajes y, por tanto, mayores evidencias existen en relación con el tipo de pruebas y exámenes que se usan como instrumento de evaluación para dar cuenta de estos logros. 

En síntesis, los resultados de esta revisión entregan elementos claves para responder a la pregunta de qué es lo que aprenden los estudiantes en los laboratorios de física. Sin embargo, todavía existen varios aspectos en cuales ahondar, por lo que no se espera que a través de este estudio se responda completamente a la pregunta de revisión. Así, los resultados de esta revisión plantean varias preguntas e inquietudes importantes que deben abordarse en futuras investigaciones. Por un lado, resulta necesario que la comunidad científico-educativa preste atención a los diseños que se definen en cada actividad de laboratorio con el objetivo de tener un currículo mayormente alineado. De esta manera, se podría tener mayor claridad sobre qué habilidades científicas se están intentando promover. Por otro lado, es importante medir la efectividad de los laboratorios de física en relación con el período académico del estudiante, con su conocimiento físico previo, con sus habilidades lingüísticas previas y, con sus experiencias previas con tecnologías. Bajo esa línea, aún no existen evidencias metodológicas claras en relación con los test estadísticos y con los tipos de instrumentos que se usan para medir logros de aprendizaje, lo que tensionaría los criterios de validez mediante los cuales se sustentan las afirmaciones. Por ejemplo, la mayoría de los estudios utiliza test o reportes escritos para dar cuenta de ganancia de aprendizaje, sin embargo, no atender y preocuparse por las habilidades lingüísticas previas de los estudiantes, podría sesgar los resultados. En ese sentido, se hace necesario contar con estudios interdisciplinares que integren diversas metodologías para entender todos los procesos mediadores que pueden afectar la ganancia de logros de los estudiantes. Tener en cuenta los elementos anteriores podría responder de manera más explícita y dar mayores garantías que sustente lo que aprenden los estudiantes en los laboratorios de física.

En este estudio no se ahondó en el diseño curricular ni las implementaciones de laboratorios reportadas en los artículos analizados (por ejemplo, laboratorios de bajo costo; laboratorios virtuales, laboratorios híbridos, entre otros). Tampoco se ahondó en los efectos mediadores que tendría el uso de tecnología en estos tipos de laboratorios. Sin embargo, con la proliferación de las tecnologías, estos tipos de laboratorios involucran la mediación informática y tecnológica como parte de su proceso y, por lo tanto, resulta necesario medir, evaluar e incorporar en futuros análisis cómo estos factores afectarían los resultados ya observados. Lo anterior es importante no solo para el desarrollo de buenas prácticas pedagógicas, sino también para un diseño metodológico coherente.

Finalmente, entre una de las limitantes metodológicas que tiene este estudio, se puede mencionar la amplia variedad mediante la cual la comunidad etiqueta o se refiere a las actividades de laboratorio. Lo anterior podría deberse a las dos corrientes que actualmente existen para referirse a una actividad de laboratorio, y que en términos epistemológicos, no son del todo claras sus diferencias y similitudes (por ejemplo, el concepto practial work se utiliza mayoritariamente en investigaciones de Europa y Australia, mientras que el término laboratory work es ampliamente utilizado por investigaciones de Estados Unidos). Sin embargo, se tiene como objetivo ahondar en estos aspectos en futuras investigaciones de manera tal de robustecer o enriquecer las afirmaciones dadas a lo largo de este estudio.

# Rereferencias

-   Ayvaci, H. S., Yildiz, M., & Bakirci, H. (2015). An evaluation of the instruction carried out with printed laboratory materials designed in accordance with 5E model: Reflection of light and image on a plane mirror. Eurasia Journal of Mathematics, Science and Technology Education, 11(6), 1677–1695. https://doi.org/10.12973/eurasia.2015.1496a
-   Beichner, R., Chabay, R., & Sherwood, B. (2010). Labs for the Matter &amp; Interactions curriculum. American Journal of Physics, 78(5), 456–460. https://doi.org/10.1119/1.3266163
-   Bergin, Murphy, & Shuilleabhain. (2018). Exploring problem-based cooperative learning in undergraduate physics labs: student perspectives. European Journal of Physics, 39(2). https://doi.org/10.1016/j.pneurobio.2007.06.001
-   Bouquet, F., Bobroff, J., Fuchs-Gallezot, M., & Maurines, L. (2017). Project-based physics labs using low-cost open-source hardware. American Journal of Physics, 85(3), 216–222. https://doi.org/10.1119/1.4972043
-   Braun, M., & Kirkup, L. (2015). Non-physics peer demonstrators in undergraduate laboratories: A study of students’ perceptions. European Journal of Physics, 37(1), 15703. https://doi.org/10.1088/0143-0807/37/1/015703
-   Day, J., Stang, J. B., Holmes, N. G., Kumar, D., & Bonn, D. A. (2016). Gender gaps and gendered action in a first-year physics laboratory. Physical Review Physics Education Research, 12(2), 1–14. https://doi.org/10.1103/PhysRevPhysEducRes.12.020104
-   Donovan, P. (2014). Closing the feedback loop: physics undergraduates’ use of feedback comments on laboratory coursework. Assessment and Evaluation in Higher Education, 39(8), 1017–1029. https://doi.org/10.1080/02602938.2014.881979
-   Douglas, S. S., Aiken, J. M., Lin, S. Y., Greco, E. F., Alicea-Muñoz, E., & Schatz, M. F. (2017). Peer assessment of student-produced mechanics lab report videos. Physical Review Physics Education Research, 13(2), 1–14. https://doi.org/10.1103/PhysRevPhysEducRes.13.020126
-   Dounas-Frazer, D. R., Stanley, J. T., & Lewandowski, H. J. (2017). Student ownership of projects in an upper-division optics laboratory course: A multiple case study of successful experiences. Physical Review Physics Education Research, 13(2), 1–22. https://doi.org/10.1103/PhysRevPhysEducRes.13.020136
-   Ellingsen, P. G., & Stovneng, J. A. (2018). Student laboratory reports: An approach to improving feedback and quality. European Journal of Physics, 39(3), 0–7. https://doi.org/10.1088/1361-6404/aaa036
-   Etkina, E., Ruibal-villasenor, M., Jordan, R., & Hmelo-silver, C. E. (2014). Transfer of Scientific Abilities : Building Habits of Mind.
-   Gandhi, P. R., Livezey, J. A., Zaniewski, A. M., Reinholz, D. L., & Dounas-Frazer, D. R. (2014). Attending to experimental physics practices and lifelong learning skills in an introductory laboratory course. https://doi.org/10.1119/1.4955147
-   Güven, G., Sülün, Y., & Çam, A. (2014). The examination of elementary preservice teachers’ reflective diaries and epistemological beliefs in science laboratory. Teaching in Higher Education, 19(8), 895–907. https://doi.org/10.1080/13562517.2014.934350
-   Halstead, E. (2016). Effects of reducing scaffolding in an undergraduate electronics lab. American Journal of Physics, 84(7), 552–556. https://doi.org/10.1119/1.4953346
-   Holmes, N. G., Olsen, J., Thomas, J. L., & Wieman, C. E. (2017). Value added or misattributed? A multi-institution study on the educational benefit of labs for reinforcing physics content. Physical Review Physics Education Research, 13(1), 1–12. https://doi.org/10.1103/PhysRevPhysEducRes.13.010129
-   Holmes, N. G., & Wieman, C. E. (2016). Examining and contrasting the cognitive activities engaged in undergraduate research experiences and lab courses. Physical Review Physics Education Research, 12(2), 1–11. https://doi.org/10.1103/PhysRevPhysEducRes.12.020103
-   Huntula, J., Sharma, M. D., Johnston, I., & Chitaree, R. (2011). A framework for laboratory pre-work based on the concepts, tools and techniques questioning method. European Journal of Physics, 32(5), 1419–1430. https://doi.org/10.1088/0143-0807/32/5/030
-   Kanim, S. E., & Subero, K. (2010). Introductory labs on the vector nature of force and acceleration. American Journal of Physics, 78(5), 461–466. https://doi.org/10.1119/1.3373923
-   Kirkup, L., Pizzica, J., Waite, K., & Srinivasan, L. (2010). Realizing a framework for enhancing the laboratory experiences of non-physics majors: From pilot to large-scale implementation. European Journal of Physics, 31(5), 1061–1070. https://doi.org/10.1088/0143-0807/31/5/008
-   Kontro, I., Heino, O., Hendolin, L., & Galambosi, S. (2018). Modernisation of the Intermediate Physics Laboratory. European Journal of Physics, 39(2), 0–16.
-   Kukliansky, I., & Eshach, H. (2014). Evaluating a Contextual-Based Course on Data Analysis for the Physics Laboratory. Journal of Science Education and Technology, 23(1), 108–115. https://doi.org/10.1007/s10956-013-9456-6
-   Leung, A. C. K., Hashemi Pour, B., Reynolds, D., & Jerzak, S. (2017). New assessment process in an introductory undergraduate physics laboratory: an exploration on collaborative learning. Assessment and Evaluation in Higher Education, 42(2), 169–181. https://doi.org/10.1080/02602938.2015.1089977
-   Liu, D., & Turkey, H. El. (2017). Exploration of task performance tests in physics laboratory. European Journal of Physics, 38(6).
-   Mellingsæter, M. S. (2014). Engineering students’ experiences from physics group work in learning labs. Research in Science and Technological Education, 32(1), 21–34. https://doi.org/10.1080/02635143.2013.853033
-   Nixon, R. S., Godfrey, T. J., Mayhew, N. T., & Wiegert, C. C. (2016). Undergraduate student construction and interpretation of graphs in physics lab activities. Physical Review Physics Education Research, 12(1), 1–19. https://doi.org/10.1103/PhysRevPhysEducRes.12.010104
-   Parappilly, M., Hassam, C., & Woodman, R. J. (2018). Race to improve student understanding of uncertainty: Using LEGO race cars in the physics lab. American Journal of Physics, 86(1), 68–76. https://doi.org/10.1119/1.5003812
-   Sarasola, A., Rojas, J. F., & Okariz, A. (2015). Training to Use the Scientific Method in a First-Year Physics Laboratory: A Case Study. Journal of Science Education and Technology, 24(5), 595–609. https://doi.org/10.1007/s10956-015-9551-y
-   Sharma, M. D., Mendez, A., Sefton, I. M., & Khachan, J. (2014). Student evaluation of research projects in a first-year physics laboratory. European Journal of Physics, 35(2), 0–17. https://doi.org/10.1088/0143-0807/35/2/025004
-   Shi, W. Z., He, X., Wang, Y., & Huan, W. (2015). Effects of lab group sex composition on physics learning. Eurasia Journal of Mathematics, Science and Technology Education, 11(1), 87–92. https://doi.org/10.12973/eurasia.2015.1308a
-   Shi, W. Z., Sun, J., Xu, C., & Huan, W. (2016). Assessing the use of smartphone in the university general physics laboratory. Eurasia Journal of Mathematics, Science and Technology Education, 12(1), 125–132. https://doi.org/10.12973/eurasia.2016.1424a
-   Sikkema, A. E., Steenwyk, S. D., & Zwart, J. W. (2010). Spinning tubes: An authentic research experience in a three-hour laboratory. American Journal of Physics, 78(5), 467–470. https://doi.org/10.1119/1.3273196
-   Sobhanzadeh, M., Kalman, C. S., & Thompson, R. I. (2017). Labatorials in introductory physics courses. European Journal of Physics, 38(065702), 0–18. https://doi.org/10.1088/1361-6404/aa8757
-   Stang, J. B., & Roll, I. (2014). Interactions between teaching assistants and students boost engagement in physics labs. Physical Review Special Topics - Physics Education Research, 10(2), 1–15. https://doi.org/10.1103/PhysRevSTPER.10.020117
-   Stanley, J. T., & Lewandowski, H. J. (2016a). Lab notebooks as scientific communication: Investigating development from undergraduate courses to graduate research. Physical Review Physics Education Research, 12(2), 1–11. https://doi.org/10.1103/PhysRevPhysEducRes.12.020129
-   Stanley, J. T., & Lewandowski, H. J. (2016b). Recommendations for the use of notebooks in upper-division physics lab courses, 45. https://doi.org/10.1119/1.5001933
-   Stanley, J. T., Su, W., & Lewandowski, H. J. (2017). Using lab notebooks to examine students’ engagement in modeling in an upper-division electronics lab course. Physical Review Physics Education Research, 13(2), 1–19. https://doi.org/10.1103/PhysRevPhysEducRes.13.020127
-   Thomas, G., & Meldrum, A. (2018). Students’ perceptions of changes to the learning environments of undergraduate physics laboratories: An empirical study. Interactive Technology and Smart Education, 15(2), 165–180. https://doi.org/10.1108/ITSE-10-2017-0045
-   Wieman, C., & Holmes, N. G. (2015). Measuring the impact of an instructional laboratory on the learning of introductory physics. American Journal of Physics, 83(11), 972–978. https://doi.org/10.1119/1.4931717
-   Wilcox, B. R., & Lewandowski, H. J. (2016). Open-ended versus guided laboratory activities: Impact on students’ beliefs about experimental physics. Physical Review Physics Education Research, 12(2), 1–8. https://doi.org/10.1103/PhysRevPhysEducRes.12.020132
-   Wilcox, B. R., & Lewandowski, H. J. (2017a). Developing skills versus reinforcing concepts in physics labs: Insight from a survey of students’ beliefs about experimental physics. Physical Review Physics Education Research, 13(1), 1–9. https://doi.org/10.1103/PhysRevPhysEducRes.13.010108
-   Wilcox, B. R., & Lewandowski, H. J. (2017b). Improvement or selection? A longitudinal analysis of students’ views about experimental physics in their lab courses. Physical Review Physics Education Research, 13(2), 1–5. https://doi.org/10.1103/PhysRevPhysEducRes.13.023101
-   Zhang, C.-L., Hou, Z.-Y., Si, Y.-C., Wen, X.-Q., & Tang, L. (2018). Application of Peer Instruction in the experiment of measuring the effective mass of spring. European Journal of Physics, 38(6), 0–9.




:::

::: panel-tabset
## English

Under Construction
:::
