<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2024-06-28">
<meta name="description" content="A review of predictive models of academic performance or at-risk students. Image created with AI.">

<title>danynash - Learning Analytics and academic performance prediction models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">danynash</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about_me.html"> 
<span class="menu-text">About me</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../myresearch.html"> 
<span class="menu-text">My Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../publications.html"> 
<span class="menu-text">Selected Publications</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials.html"> 
<span class="menu-text">Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../lessons.html"> 
<span class="menu-text">Lessons</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Learning Analytics and academic performance prediction models</h1>
</div>

<div>
  <div class="description">
    A review of predictive models of academic performance or at-risk students.<br>
    <em>Image created with AI</em>.
  </div>
</div>


<div class="quarto-title-meta column-page">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 28, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Español</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">English</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<section id="introducción" class="level1">
<h1>1. Introducción</h1>
<p>Desde inicios de los XX hasta la actualidad, la psicología ha realizado importantes estudios en el entendimiento del aprendizaje, tanto en la infancia, como en la etapa adolescente (Shaffer &amp; Kipp, 2010). Diferentes teorías han surgido desde la psicología que explicarían cómo se produce el aprendizaje y que factores internos como externos lo mediarían. En efecto, teorías cognitivistas, conductuales, social-cognitivista y constructivistas (McInerney, 2005) han surgido y tomado protagonismo en el intento de explicar este complejo fenómeno personal y social. A su vez, diferentes investigaciones se han enfocado en entender los procesos de aprendizaje dentro el aula, estudiando cómo factores personales e inter-personales impactarían en el rendimiento final de los estudiantes, entre ellos destacan: estudios de autoeficacia (Bandura, 1977), compromiso (Miller, Greene, Montalvo, Ravindran, &amp; Nichols, 1996) y componentes emocionales (Tyng, Amin, Saad, &amp; Malik, 2017), entre otras.</p>
<p>En este mismo intento de comprender el aprendizaje y los contextos donde este se produce, la proliferación del uso de tecnologías también ha contribuido (Castro, Vellido, Nebot, &amp; Mugica, 2007). Cabe señalar que dicha preocupación se enmarca en contextos educacionales que han tenido cambios sustanciales debido a esta explosión en el uso de las tecnologías. Entre estos nuevos contextos educacionales se pueden mencionar (1) aprendizaje virtual, (2) combinado, y (3) a distancia. Como consecuencia, diferentes disciplinas han emergido para intentar comprender estos nuevos contextos educacionales. Efectivamente, desde el 2000 han surgido disciplinas como Educational Data Mining (EDM) (Romero &amp; Ventura, 2010), Academyc Analytics (AA) (Goldstein &amp; Katz, 2005) y LA (Siemens, 2013). Estas disciplinas, usando sofisticados algoritmos computaciones, han intentado caracterizar y comprender los procesos de aprendizaje de los estudiantes. Sin embargo, existen distinciones entre estas tres disciplinas, y se argumenta que LA estaría ligada de manera más profunda y concreta en los aprendizajes de los estudiantes y en los contextos donde este ocurre (Ferguson, 2012).</p>
<p>Enfocando la atención en LA, esta herramienta desde su origen (2011 aproximadamente) ha ido en continuo crecimiento, y, hasta la fecha, ha captado la atención de múltiples investigadores con el fin de entender, por un lado, los procesos de aprendizaje de los estudiantes, y, por otro, la de tomar decisiones a nivel institucional para mejorar las experiencias y los procesos de aprendizaje de los estudiantes. En base a lo anterior, se puede definir LA como el proceso de medir, recolectar, analizar y reportar datos de estudiantes y de sus contextos, con el propósito de entender y optimizar el aprendizaje y los ambientes en los cuales éste ocurre (Clow, 2013). Debido al reciente surgimiento de LA, y a su manera positivista de interpretar la realidad en los contextos educacionales, todavía existen desafíos que enfrentar. Entre estos desafíos se encuentra el desconocimiento en el impacto en el aprendizaje y la falta de integración que suponen los aspectos computacionales de este campo con las investigaciones existente en el aprendizaje y educación (Gašević et al., 2015). Otro de los desafíos que ha enfrentado LA es la creación de un modelo que permita a los investigadores tener mayor conocimiento sobre los dominios o dimensiones en los cuales se enmarca. La importancia de establecer un modelo de LA es que, a partir de éste, es posible delimitar el ciclo de vida de los procesos que involucra una investigación en este campo (Rojas Castro, 2017). Enfocándose en un modelo para LA, el trabajo desarrollado por Greller y Drachsler (2012) ha podido identificar seis grandes dimensiones para este, estos son: (i) Instrumentos; (ii) datos; (iii) objetivos; (iv) partes interesadas; (v) limitaciones internas; y, (vi) limitaciones externas. Estas dimensiones representarían de cierta forma los delimitadores del campo en el sentido de que precisarían las fronteras, o más bien, los elementos que separan y distinguen los trabajos de la comunidad (Rojas Castro, 2017).</p>
<p>Ahora bien, es posible identificar o establecer focos de acción que sigue la línea LA. Estos ejes conversarían o estarían relacionados, en un menor o mayor grado, con cada una de las dimensiones comentadas anteriormente. Estos ejes son: (i) Problemas orientado a la pedagogía; (ii) Contextualización del aprendizaje, (iii) Aprendizaje en Red y (iv) Manejo de recursos educativos (Papamitsiou &amp; Economides, 2016). Centrándonos en los primeros dos ejes, actualmente se pueden encontrar técnicas en LA que permiten abordarlas. Entre estas técnicas destacan los modelos que describen el proceso, la práctica y los desafíos del uso de modelos predictivos en la enseñanza, como también, técnicas que permiten identificar relaciones causales interpretables entre constructos que pueden ser inferidas a partir de los datos (Lang, 2017).</p>
<p>En base a lo explicado anteriormente, uno de los objetivos que busca esta revisión de literatura es abordar los dos primeros ejes expuestos. Para ello, se tiene como objetivo evidenciar, a través de trabajos empíricos, cuáles son los métodos o modelos utilizados por la comunidad de LA. En particular, este trabajo está enfocado en técnicas o métodos que se focalicen en la detección de estudiantes en riesgo, debido a que estos tienen mayor probabilidad de deserción en el sistema educativo. Se entenderá por estudiantes en riesgo, aquellos estudiantes que tienen una alta posibilidad de reprobar un curso o semestre dentro del contexto educativo (Wang &amp; Newlin, 2002). De esta manera, a través de LA se tendría la capacidad de identificar tempranamente a estudiantes en riesgo de fracasar académicamente (o desertar), permitiendo tomar acciones e intervenciones oportunas para mejorar los procesos de aprendizaje y enseñanza de manera tal de apuntar en una mejora de la calidad de esta y en la retención de estudiantes.</p>
<p>En definitiva, este estudio estará guiado por las siguientes preguntas de investigación:</p>
<ol type="1">
<li>¿Qué técnicas o métodos se han utilizado en estudios empíricos para predecir estudiantes en riesgo?</li>
<li>¿Qué implicancias a nivel de investigación y de prácticas se pueden desprender de estos estudios empíricos?</li>
</ol>
<p>Este texto se dividirá de la siguiente manera. Sección II describirá la metodología, comentando los criterios de inclusión y exclusión de los manuscritos. Los resultados de esta revisión de literatura se abordarán en la Sección III y serán discutidos en la Sección IV. Se finalizará esta revisión con la sección conclusión.</p>
</section>
<section id="metodología" class="level1">
<h1>2. Metodología</h1>
<p>El propósito de esta revisión bibliográfica es examinar estudios empíricos que incorporen como eje central la predicción de rendimiento académico o estudiantes en riesgo. En relación a lo anterior, esta revisión bibliográfica sólo se centrará en trabajos empíricos en inglés con foco exclusivo en educación superior.</p>
<p>Se realizó la búsqueda en dos bases de datos: Web of Science (WOS) y Journal of Learning Analytics (JLA). Las palabras claves para realizar esta búsqueda fueron: Learning Analytics, performance, risk, academic success y predict. En la <a href="#tbl-Tabla_1" class="quarto-xref">Table&nbsp;1</a> se encuentra el detalle del código de búsqueda que se utilizó para la base de datos WOS y JAL.</p>
<div id="tbl-Tabla_1" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Tabla_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Código de búsqueda en WOS y JLA
</figcaption>
<div aria-describedby="tbl-Tabla_1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Base de datos</th>
<th>Código de Búsqueda</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>WOS</td>
<td>TS=(“Learning” NEAR/0 “Analytics” AND predict* AND (performance* OR *risk OR “academic” NEAR/0 “success” ) and dt=article AND wc=(EDUCATION EDUCATIONAL RESEARCH EDUCATION) AND PY=2013-2018</td>
</tr>
<tr class="even">
<td>JLA</td>
<td>performance* OR “academic success”OR risk* OR success</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A continuación, se listan los criterios de inclusión-exclusión</p>
<ul>
<li><p>Artículos vinculados exclusivamente con LA.</p></li>
<li><p>Publicaciones realizadas entre los años 2013 y 2018. Lo anterior con el fin de realizar una revisión de literatura lo más actualizada.</p></li>
<li><p>Artículos que tengan revisión de pares y que cumplan con los estándares de calidad.</p></li>
<li><p>Sólo se consideraron artículos en área WOS EDUCATION EDUCATIONAL RESEARCH EDUCATION. Esto sólo aplica para la base de datos WOS.</p></li>
<li><p>Alguna de las palabras claves con la que se realizó la búsqueda debían estar presentes en alguna de las siguientes secciones: título del artículo, resumen o palabras claves.</p></li>
<li><p>Sólo se consideraron artículos empíricos, excluyendo publicaciones teóricas que se enfocaran en la discusión o debate sobre la identificación de estudiantes en riesgo.</p></li>
</ul>
<p>Al realizar la búsqueda en cada base de datos, se obtuvo un resultado total de 38 artículos para la base de datos WOS y 19 para JLA. Finalmente, luego de aplicar los criterios de inclusión-exclusión comentados anteriormente, la cantidad de artículos se redujo a 16 en total.</p>
</section>
<section id="resultados" class="level1">
<h1>3. Resultados</h1>
<p>En la <a href="#tbl-table2" class="quarto-xref">Table&nbsp;2</a> se encuentra el listado de los trabajos analizados mostrando el tamaño de la muestra, modalidad de análisis (a nivel de curso o de facultad), modalidad de instrucción, área disciplinar y tipo de variables involucradas.</p>
<div id="tbl-table2" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-table2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Resumen de investigaciones relacionadas con predictores educativos
</figcaption>
<div aria-describedby="tbl-table2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<table class="table cell table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Investigación</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">N</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Nivel</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Modalidad_instrucción</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Área_disciplinar</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Objetivo_de_estudio</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Tipo_de_variables</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Zacharis, 2015</td>
<td style="text-align: right;">134</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Blended</td>
<td style="text-align: left;">Ciencias de la computación</td>
<td style="text-align: left;">Identificar predictores significativos</td>
<td style="text-align: left;">Compromiso (LMS,Moodle); Rendimiento Académico</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jo, Kim, &amp; Yoon, 2015</td>
<td style="text-align: right;">200</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Online (solo para adultos)</td>
<td style="text-align: left;">Finanzas y negocios - 'Credit Derivative'</td>
<td style="text-align: left;">Identificar predictores significativos</td>
<td style="text-align: left;">Compromiso (LMS); Rendimiento Académico</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gašević, Dawson, Rogers, &amp; Gasevic, 2016</td>
<td style="text-align: right;">4134</td>
<td style="text-align: left;">Nivel de curso &amp; Facultad</td>
<td style="text-align: left;">Blended</td>
<td style="text-align: left;">Ciencias de la Salud; Educación; Arte y Ciencias Sociales; Tecnología e información; Ingeniería y el ambiente; Finanzas</td>
<td style="text-align: left;">Identificar predictores significativos</td>
<td style="text-align: left;">Compromiso (LMS,Moodle); Rendimiento Académico; Sociodemográfico</td>
</tr>
<tr class="even">
<td style="text-align: left;">You, 2016</td>
<td style="text-align: right;">530</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">e-learning</td>
<td style="text-align: left;">Diversas facultades - 'Introduction to color' (curso electivo)</td>
<td style="text-align: left;">Identificar predictores significativos; Crear sistemas tempranos de aviso</td>
<td style="text-align: left;">Compromiso (LMS)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marbouti, Diefes-Dux, &amp; Madhavan, 2016</td>
<td style="text-align: right;">3063</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Presencial</td>
<td style="text-align: left;">Ingeniería - Herramientas computacionales para la resolución de problemas</td>
<td style="text-align: left;">Evaluar modelos</td>
<td style="text-align: left;">Rendimiento Académico; Logros de objetivos de aprendizaje</td>
</tr>
<tr class="even">
<td style="text-align: left;">de Barba, Kennedy, &amp; Ainley, 2016</td>
<td style="text-align: right;">862</td>
<td style="text-align: left;">Nivel curso b</td>
<td style="text-align: left;">MOOC</td>
<td style="text-align: left;">Macro-economía</td>
<td style="text-align: left;">Identificar predictores significativos</td>
<td style="text-align: left;">Participación (Video, quiz); Motivacional</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ellis, Han, &amp; Pardo, 2017</td>
<td style="text-align: right;">145</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Blended</td>
<td style="text-align: left;">Ingeniería</td>
<td style="text-align: left;">Identificar predictores significativos</td>
<td style="text-align: left;">Compromiso (LMS); Cuestionario Student´s Approaches to Learning</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hart &amp; Ganley, 2017</td>
<td style="text-align: right;">85</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Flipped</td>
<td style="text-align: left;">Matemáticas - Cálculo III</td>
<td style="text-align: left;">Identificar predictores significativos; Crear sistemas tempranos de aviso</td>
<td style="text-align: left;">Compromiso (LMS); Intra-personal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pardo, Han, &amp; Ellis, 2017</td>
<td style="text-align: right;">145</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Blended</td>
<td style="text-align: left;">Ingeniería - Introducción a sistemas de computadores</td>
<td style="text-align: left;">Combinación con enfoques de aprendizaje</td>
<td style="text-align: left;">Compromiso (LMS); Aprendizaje autorregulado</td>
</tr>
<tr class="even">
<td style="text-align: left;">Howard, Meehan, &amp; Parnell, 2018</td>
<td style="text-align: right;">144</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Curso online &amp; 24h de taller presencial</td>
<td style="text-align: left;">Matemáticas - estadística</td>
<td style="text-align: left;">Evaluar modelos</td>
<td style="text-align: left;">Compromiso (LMS); Datos sociodemográficos; Rendimiento Académico</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T Lu et al., 2018</td>
<td style="text-align: right;">59</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Blended</td>
<td style="text-align: left;">Matemáticas - Cálculo</td>
<td style="text-align: left;">Identificar predictores significativos</td>
<td style="text-align: left;">Online Assessment System; Compromiso</td>
</tr>
<tr class="even">
<td style="text-align: left;">Choi, Lam, Li, &amp; Wong, 2018</td>
<td style="text-align: right;">1075</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Face-to-face</td>
<td style="text-align: left;">Finanzas – 'Quantitative Methods for Decision Making'</td>
<td style="text-align: left;">Identificar predictores significativos; Crear sistemas tempranos de aviso</td>
<td style="text-align: left;">Interacción en clases (CLIKERS); Sociodemográficos; Creencias y expectativas</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saqr, Fors, &amp; Tedre, 2018</td>
<td style="text-align: right;">35</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Blended</td>
<td style="text-align: left;">Medicina</td>
<td style="text-align: left;">Identificar predictores significativos</td>
<td style="text-align: left;">Estructuras sociales (Moodle); Rendimiento académico; Comprensión, análisis y aplicación</td>
</tr>
<tr class="even">
<td style="text-align: left;">Casey &amp; Azcona, 2017</td>
<td style="text-align: right;">111</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Presencial con módulos virtuales</td>
<td style="text-align: left;">Ciencias de la computación</td>
<td style="text-align: left;">Identificar predictores significativos; Crear sistemas tempranos de aviso</td>
<td style="text-align: left;">Métricas de teclas (desde navegador); Rendimiento académico</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Junco &amp; Clem, 2015</td>
<td style="text-align: right;">236</td>
<td style="text-align: left;">Nivel curso</td>
<td style="text-align: left;">Presencial con módulos virtuales</td>
<td style="text-align: left;">Psicología; Contabilidad; Leyes; Gestión de operaciones; Teoría de la evolución</td>
<td style="text-align: left;">Explorar patrones de lectura; Identificar predictores significativos</td>
<td style="text-align: left;">Análisis de texto; Rendimiento académico; Datos sociodemográficos</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
<section id="muestra-de-estudio" class="level3">
<h3 class="anchored" data-anchor-id="muestra-de-estudio">3.1 Muestra de estudio</h3>
<p>Tal como se aprecia en la Tabla 2, solo uno de los trabajos empíricos analizados (Gašević, Dawson, Rogers, &amp; Gasevic, 2016) realiza un análisis de predicción tanto a nivel de facultad y de cursos, abarcando una muestra de tamaño N=4134. Respecto a los otros estudios, todos se centran en análisis en contextos particulares, es decir, a nivel de cursos. Por otro lado, Blended courses el tipo de modalidad de instrucción que más predomina, seguido de cursos de carácter masivos online (MOOCs). Solamente uno de los estudios analizados es de carácter presencial (Marbouti, Diefes-Dux, &amp; Madhavan, 2016) y con un gran número de estudiantes analizados: N=3063. Finalmente, el común denominador en términos de número de estudiantes estudiados, lo son trabajos que no superan los 1000 estudiantes, encontrándose siete estudios que analizan una muestra menor a 300 estudiantes (Hart &amp; Ganley, 2017; Howard, Meehan, &amp; Parnell, 2018; Jo, Kim, &amp; Yoon, 2015; Pardo, Han, &amp; Ellis, 2017; T Lu et al., 2018; Zacharis, 2015) y dos estudios abordan muestras mayores a 300 y menores a 1000 (de Barba, Kennedy, &amp; Ainley, 2016; You, 2016). Finalmente, sólo 3 estudios empíricos analizan una muestra sobre 1000 estudiantes (Choi, Lam, Li, &amp; Wong, 2018; Gašević et al., 2016; Marbouti et al., 2016).</p>
<p>Con respecto al área disciplinar abordada por estos estudios empíricos, mayoritariamente se abordan áreas del ámbito científico. Mientras que solo dos investigaciones abordan áreas desde las ciencias sociales (Junco &amp; Clem, 2015; You, 2016).</p>
</section>
<section id="objetivos-de-estudio-abordados-en-los-artículos-empíricos" class="level3">
<h3 class="anchored" data-anchor-id="objetivos-de-estudio-abordados-en-los-artículos-empíricos">3.2 Objetivos de estudio abordados en los artículos empíricos</h3>
<p>Se pueden identificar diversos objetivos de investigación en los manuscritos analizados. Entre estos objetivos los que más destacan son: (i) Encontrar cuáles son los predictores más importantes de las notas finales de los estudiantes; (ii) Evaluar modelos;(iii) Crear sistemas tempranos de avisos; y, (iv) Combinar técnicas de LA con la teoría de aproximación al aprendizaje. A continuación, se detallan cada uno de estos objetivos, incorporando los trabajos empíricos, como también, las variables que se utilizaron:</p>
<ol type="i">
<li><p><strong>Predictores más importantes</strong>: Estos estudios declaran explícitamente este objetivo como uno de los ejes centrales de sus investigaciones estudiantes (Casey &amp; Azcona, 2017; Choi, Lam, Li, &amp; Wong, 2018; de Barba, Kennedy, &amp; Ainley, 2016; Ellis, Han, &amp; Pardo, 2017; Gašević et al., 2016; Hart &amp; Ganley, 2017; Jo, Kim, &amp; Yoon, 2015; Junco &amp; Clem, 2015; Saqr et al., 2018; T Lu et al., 2018; You, 2016; Zacharis, 2015). Entre las variables predictoras que se consideran en los modelos, destacan las de compromiso (<em>engagement</em>), abordado por el 50% de los estudios empíricos. Principalmente, esta variable se mide a travése de las actividades que realizan los estudiantes en los Learning Management Systems (LMS) o MOOCs. Ahora bien, variables sociodemográficas se incorporan en cuatro estudios (Choi et al., 2018; Gašević et al., 2016; Howard, Meehan, &amp; Parnell, 2018; Junco &amp; Clem, 2015). Adicionalmente, también se observan otro tipo de variables como potenciales predictores del rendimiento académico, tales como del tipo instruccionales, motivación (de Barba et al., 2016), aproximaciones al aprendizaje (Ellis, Han, &amp; Pardo, 2017; Pardo, Han, &amp; Ellis, 2017) y finalmente, datos que provienen de las acciones a través de Clickers o métricas de teclas (Casey &amp; Azcona, 2017; Choi et al., 2018).</p></li>
<li><p><strong>Evaluar modelos</strong>: Este objetivo fue abordado como eje central en sólo dos estudios empíricos (Howard et al., 2018; Marbouti et al., 2016) . Por un lado, el estudio de Marbouti et al.&nbsp;(2016) tiene como objetivo contrastar diferentes modelos que para identificar estudiantes en riesgo. Esto se hace a través del rendimiento de sus notas finales – estudiantes en riesgo serían aquellos que tendrían altas posibilidades de reprobar un curso-. Las variables predictores que se usan son los logros de objetivos de aprendizaje (en la modalidad presencial). Por otro lado, el estudio de Howard et al.&nbsp;(2018) tiene como objetivo explorar posibles modelos que predigan de manera temprana estudiantes en riesgo de reprobar. Se utilizan variables de compromiso a través de las acciones de los estudiantes en los MOOCs, de participación (en talleres) y notas de exámenes online.</p></li>
<li><p><strong>Crear sistemas tempranos de avisos</strong>: Este objetivo fue declarado como eje secundario en los estudios analizados (Casey &amp; Azcona, 2017; Choi et al., 2018; Hart &amp; Ganley, 2017; You, 2016). A grandes rasgos, a través de los modelos predictivos analizados, estos estudios tienen como intención la generación de recomendaciones para implementar un sistema de alerta temprano que permita identificar y ayudar a posibles estudiantes en riesgo.</p></li>
<li><p><strong>Combinar técnicas de LA y aproximación al aprendizaje</strong>: Estos estudios (Ellis, Han, &amp; Pardo, 2017; Pardo et al., 2017), establencen una relación conceptual que permita conectar las actividades en línea con la teoría de los enfoques de aprenizaje. Utilizan variable predictor del rendimiento académico los enfoques de aprendiaje superficial y profundo junto con variables de actividades en línea. Estos estudios empíricos, según se declara, aportarían conocimiento para ayudar a dilucidar el actual debate que se tiene en la comunidad de LA con respecto a una falta de incorporación del componente mismo del aprendizaje en el diseño de LA.</p></li>
</ol>
</section>
<section id="métodos-y-grado-de-predictibilidad" class="level3">
<h3 class="anchored" data-anchor-id="métodos-y-grado-de-predictibilidad">3.3 Métodos y grado de predictibilidad</h3>
<p>Uno de los factores relevantes en LA lo conforman los métodos o herramientas de Minería de Datos. Estas herramientas permiten realizar procesos de descripción e inferencias de los datos educacionales que se recopilan. El uso de estos métodos varía enormemente dentro de la comunidad de LA, y su aplicabilidad en la predicción de rendimiento académico depende de diversos factores, tales como, el número de la muestra a analizar, el tipo de datos que se está analizando, la cantidad de datos que se desean procesar y analizar, requisitos previos que requiere una determinada muestra para aplicar cierto algoritmo, entre otros (Romero &amp; Ventura, 2010). Por las razones comentadas anteriormente, es relevante evidenciar en la literatura qué métodos se han utilizado en la predicción de rendimiento académico dentro del diseño de LA. Los resultados que se expondrán en esta sección responderían explícitamente a la pregunta de investigación número 1. En la <a href="#tbl-table3" class="quarto-xref">Table&nbsp;3</a> se muestra un resumen de los métodos o algoritmos utilizados por las investigaciones analizadas.</p>
<div id="tbl-table3" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-table3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Resultado de los métodos o algoritmos de Míneria de Datos utilizados en los estudios análizados. La variable predictora en todos los casos lo es la nota final del curso
</figcaption>
<div aria-describedby="tbl-table3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 69%">
</colgroup>
<thead>
<tr class="header">
<th>Métodos</th>
<th>Estudios</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Análisis de correlaciones</td>
<td>(Zacharis, 2015);(Jo, Kim, &amp; Yoon, 2015);(You, 2016);(de Barba, Kennedy, &amp; Ainley, 2016);(Ellis et al., 2018);(Hart &amp; Ganley, 2017);(Pardo, Han, &amp; Ellis, 2017);(Choi, Lam, Li, &amp; Wong, 2018);(Saqr, Fors, &amp; Tedre, 2018);(Junco &amp; Clem, 2015)</td>
</tr>
<tr class="even">
<td>Regresión lineal múltiple</td>
<td>(Zacharis, 2015);(Jo, Kim, &amp; Yoon, 2015);(Gašević, Dawson, Rogers, &amp; Gasevic, 2016);(You, 2016);(Hart &amp; Ganley, 2017);(Pardo, Han, &amp; Ellis, 2017);(T Lu et al., 2018);(Choi, Lam, Li, &amp; Wong, 2018);(Saqr, Fors, &amp; Tedre, 2018);(Junco &amp; Clem, 2015)</td>
</tr>
<tr class="odd">
<td>Regresión logística</td>
<td>(Zacharis, 2015);(Gašević, Dawson, Rogers, &amp; Gasevic, 2016);(Marbouti, Diefes-Dux, &amp; Madhavan, 2016);(Choi, Lam, Li, &amp; Wong, 2018);(Saqr, Fors, &amp; Tedre, 2018);(Casey &amp; Azcona, 2017)</td>
</tr>
<tr class="even">
<td>Modelo de ecuaciones estructurales</td>
<td>(de Barba, Kennedy, &amp; Ainley, 2016)</td>
</tr>
<tr class="odd">
<td>Análisis factorial</td>
<td>(Ellis et al., 2018);(Pardo, Han, &amp; Ellis, 2017)</td>
</tr>
<tr class="even">
<td>Análisis de clustering</td>
<td>(Ellis et al., 2018);(Pardo, Han, &amp; Ellis, 2017)</td>
</tr>
<tr class="odd">
<td>Support Vector Machine</td>
<td>(Marbouti, Diefes-Dux, &amp; Madhavan, 2016);(Howard, Meehan, &amp; Parnell, 2018);(Casey &amp; Azcona, 2017)</td>
</tr>
<tr class="even">
<td>Arboles de decisión Redes neuronales - Naïve Bayes Classifier - K-Nearest Neigbhor</td>
<td>Marbouti, Diefes-Dux, &amp; Madhavan, 2016);(Howard, Meehan, &amp; Parnell, 2018);(Casey &amp; Azcona, 2017)</td>
</tr>
<tr class="odd">
<td>Network Analysis</td>
<td>(Saqr, Fors, &amp; Tedre, 2018)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Tal como se aprecia en la <a href="#tbl-table3" class="quarto-xref">Table&nbsp;3</a>, se utilizan diversos métodos de Minería de Datos (Romero &amp; Ventura, 2010). La gran mayoría (10 de los 16 artículos) realiza análisis que involucra aplicar una regresión lineal múltiple (o logístico dependiendo del tipo de dato a predecir) como herramienta principal para predecir rendimiento académico, acompañado de análisis de correlaciones para identificar relaciones significativas entre las variables de involucradas. Comentando estudios que tiene mayor grado de predicción en el rendimiento académico utilizando modelos de regresión lineal, destaca el estudio de Zacharis (2015), explicando un 52% de la varianza total. Las variables que provienen de los LMS: Reading y posting messages, explican alrededor del 37% de la nota final. Lo sigue el estudio de (Jo et al., 2015), que logra explicar un 37% de la varianza. En este estudio, solo la variable proxy regularity of learning fue significativa en el rendimiento final de los estudiantes. Para el caso del trabajo de Gašević et al.&nbsp;(2016), las variables LMS explican un 16% de la varianza total. Ahora bien, al utilizar un modelo secundario un análisis de regresión logística, se identifican que las características propias del estudiante (variables sociodemograficas), en conjunto con los datos de rastreo de este (interacción con los LMS), mejora substancialmente el poder de predictibilidad en el desempeño académico. Por otro lado, en el trabajo de You (2016), se explica un 58.1% de la variabilidad total de la nota final, indicando que las variables regular study time, late submissiones time, sessions time y proof of reading, tienen mayor significancia en el modelo. Finalmente, en el estudio de Pardo et al.&nbsp;(2017), los predictores test anxiety, engagment with resources y multiple-choice question, explicarían un 32% de la variabilidad total. Por otro lado, comentando investigaciones que comparan diferentes modelos en la predicción de rendimiento académico, el trabajo realizado por Marbouti et al.&nbsp;(2016), concluye que ninguno de los modelos de predicción tiene una precisión aceptable tanto para estudiantes que aprueban como para los que fracasan en un curso. Por lo anterior, se utiliza un Ensemble con los tres modelos que tienen mayor precisión: Naïve Bayes Classifier, Support Vector Machine y K-Nearest Neigbhor. En definitiva, se concluye que este Ensemble model pudo identificar a estudiantes en riesgo y predecir el éxito de los estudiantes con un 85% de precisión. Por otro lado, el estudio de Howard et al.&nbsp;(2018) concluye que el algoritmo BART es el que mejor desempeño tiene al predecir las notas finales. En definitiva, con el objetivo de identificar tempranamente estudiantes en riesgo, este estudio concluye que la semana 5-6 es el momento crítico en el semestre de curso, según el cual, los modelos de predicción tienen predicciones razonablemente precisas. De este modelo, se desprende que la variable con mayor ponderación lo es Continuous assessment.</p>
</section>
<section id="discusión" class="level3">
<h3 class="anchored" data-anchor-id="discusión">4 Discusión</h3>
<p>Si bien los tipos de estudios empíricos analizados incorporan, en general, diferentes variables predictores del desempeño académico, como también, diferentes métodos para predecirla, es posible trazar los alcances o implicancias que generan estos resultados tanto a un nivel de investigación como en las prácticas instruccionales. En las siguientes secciones se comentarán las implicancias que tendría en estos dos niveles, respondiendo de esta manera, a la pregunta de investigación número 2.</p>
<section id="implicancias-a-nivel-de-investigación" class="level4">
<h4 class="anchored" data-anchor-id="implicancias-a-nivel-de-investigación">4.1 Implicancias a nivel de investigación</h4>
<p>Variadas pueden ser las implicancias a nivel de investigación en el diseño de LA que se pueden comentar al analizar los estudios empíricos de esta revisión. Se pueden mencionar tres factores a considerar en futuras investigaciones de LA. En primer lugar, destaca la necesidad imperativa de considerar aspectos instruccionales cuando se desarrollan modelos predictivos, tal como se evidencia en los trabajos (Gašević et al., 2016; Marbouti et al., 2016). En segundo lugar, identificar o incorporar características poco convencionales en el diseño de LA puede aportar bastante en mejorar la precisión de los modelos de LA. Entre estas características destacan: (i) factores auto-regulatorios de los estudiantes(You, 2016), que pueden ser medidas a través de cuestionarios o indirectamente a partir de datos de LMS; (ii) elementos que den cuenta de las aproximaciones de aprendizaje de los estudiantes (Ellis, Han, Pardo, et al., 2017; Pardo et al., 2017). Estas dos características (entre varias más) son elementos que ayudarán en el debate teórico de LA. En tercer y último lugar, tal como se abordó como segundo objetivo en algunos de los estudios analizados (Choi et al., 2018; Hart &amp; Ganley, 2017; You, 2016), futuros trabajos deberán investigar con qué frecuencia se deben ejecutar los modelos y qué momentos son los oportunos para informar a los estudiantes.</p>
</section>
<section id="implicancias-a-nivel-práctico" class="level4">
<h4 class="anchored" data-anchor-id="implicancias-a-nivel-práctico">4.2 Implicancias a nivel práctico</h4>
<p>Los resultados que se desprenden de los modelos predictivos analizados en esta revisión, podrían impactar de manera directa tanto a nivel instruccional como a nivel institucional. Desde una perspectiva instruccional, los resultados derivados de los modelos enfocados en cursos específicos pueden proveer al profesor una mejor comprensión sobre los factores que afectan el éxito académico de los estudiantes, de modo que los hallazgos puedan ser interpretados en las condiciones especificas del curso que se imparte, como también, a mejorar la práctica docente. Por ejemplo, los resultados obtenidos en el trabajo de Pardo et al.&nbsp;(2017), entregan información valiosa a los docentes con respecto al nivel de ansiedad que tienen los alumnos al tomar el curso (predictor significativo en el rendimiento de los estudiantes). También, tal como se mostró (You, 2016), tener conocimiento sobre las regularidades en el estudio que tienen los alumnos a lo largo del semestre, puede ser un factor relevante a considerar en las prácticas pedagógicas, de manera tal, que toda modificación que se decida impacten positivamente en los desempeños de los estudiantes. Sin embargo, se debe tener cuidado con sobre generalizar los resultados de trabajos empíricos, ya que, dependiendo de la naturaleza individual de los cursos, se deben tomar diferentes decisiones para intervenirlos de manera apropiada.</p>
<p>A nivel institucional, todavía existen demasiadas preguntas que responder, y así se hace notar en los estudios analizados, en la que sólo uno de los estudios aborda el tema de cómo los resultados impactarían a nivel institucional (Gašević et al., 2016). En ese sentido, se argumenta que las instituciones de educación superior deben proceder con cautela al externalizar las capacidades construidas a partir de LA para garantizar que sus prioridades estratégicas en el desarrollo continuo de la práctica, la calidad y los aspectos socioculturales del aprendizaje y la enseñanza no se vean comprometidas. Además, las instituciones deben tener presente que toda generalización que se hace a partir de los modelos predictivos, pueden no ajustarse a las necesidades particulares de cada contexto, pero que representarían, a priori, una buena estratégica costo-efectiva para identificar estudiantes en riesgos.</p>
<p>Finalmente, a partir de los estudios empíricos analizados, surgen preguntas con respecto a al valor de considerar aspectos instruccionales en los procesos de aprendizaje de los estudiantes, tales como ¿Cuándo y con quién debería intervenir el instructor? ¿Cómo deberían asignarse los recursos para proporcionar ayuda efectiva a los estudiantes en riesgo? ¿Qué aspectos instruccionales se han abordado en estudios de LA de manera tal de ayudar en la toma de decisiones de estos?</p>
</section>
</section>
<section id="conclusión" class="level3">
<h3 class="anchored" data-anchor-id="conclusión">5 Conclusión</h3>
<p>Esta revisión de literatura se centró en modelos predictivos de rendimiento académico usando técnicas de Learning Analytics. Para ello, esta revisión centró su búsqueda en las bases de datos WOS y JLA. De los 16 artículos obtenidos, se evidencia que la mayoría de los estudios se enfocan en muestras que provienen del área científica. Además, el nivel de análisis de todos los artículos se centra particularmente en cursos, mientras que solo uno de los trabajos estudiados lo hace a nivel de facultad. Ahora bien, con respecto a los objetivos que se identificaron en estos estudios de Learning Analytics, destaca mayoritariamente la predicción de variables significativas en el rendimiento académico. Entre estas variables destacan las de compromiso y sociodemográficas. Con respecto a los métodos utilizados, se identificaron dos grupos: (i) análisis de correlación y regresión lineal múltiple y logística para predecir rendimiento académico; y (ii) modelos Ensemble, en el que, mediante la integración de varios algoritmos, tales como redes neuronales, Support Vector Machine y Naïve Bayes Classifier, permitieron mejorar el nivel de predicción del rendimiento académico. Estos resultados responden a la pregunta de investigación número 1. Con respecto a las implicancias a nivel práctico, los estudios analizados se centran mayoritariamente en aportes a nivel instruccional, en el que, mediante la identificación de variables significativas en el rendimiento académico, permitiría a los profesores tomar decisiones oportunas para ayudar a estudiantes con mayor probabilidad de reprobar. Sin embargo, aportes a nivel institucional son relativamente escasos en las investigaciones estudiadas. Finalmente, con respecto a las implicancias a nivel de investigación, uno de los factores que mayor importancia se identificó es la falta de incorporación de variables instruccionales en los modelos de predicción, como también, la adición de variables relevantes en el rendimiento académico, como lo son: variables que midan autorregulación y enfoque de aprendizaje. En base a lo anterior, se respondería a la pregunta de investigación número 2. Una de los aspectos que no consideró en esta revisión, y que debe ser abordada en futuras revisiones de literatura corresponde a los supuestos epistemológicos en los constructos que se utilizan como predictores del rendimiento académico. Esto que sin lugar a dudas contribuiría a un mayor conocimiento sobre cómo estos constructos, como por ejemplo de compromiso, son abordados en las diferentes investigaciones.</p>
</section>
<section id="referencia" class="level3">
<h3 class="anchored" data-anchor-id="referencia">Referencia</h3>
<ul>
<li>Almosallam, E. A., &amp; Ouertani, H. C. (2014). Learning Analytics: definitions, applications and related fields. Proceedings of the First International Conference on Advanced Data and Information Engineering (DaEng-2013), Lecture Notes in Electrical Engineering, 285, 721–730. https://doi.org/10.1007/978-981-4585-18-7</li>
<li>Bandura, A. (1977). Self-Efficacy: Toward a Unifying Theory of Behavioral Change. The Psychological Review, 84, 191–215. https://doi.org/http://dx.doi.org/10.1016/0146-6402(78)90002-4</li>
<li>Casey, K., &amp; Azcona, D. (2017). Utilizing student activity patterns to predict performance. International Journal of Educational Technology in Higher Education, 14(1). https://doi.org/10.1186/s41239-017-0044-3</li>
<li>Castro, F., Vellido, A., Nebot, À., &amp; Mugica, F. (2007). Applying Data Mining Techniques to e-Learning Problems. In L. C. Jain, R. A. Tedman, &amp; D. K. Tedman (Eds.), Evolution of Teaching and Learning Paradigms in Intelligent Environment (pp.&nbsp;183–221). Berlin, Heidelberg: Springer Berlin Heidelberg. https://doi.org/10.1007/978-3-540-71974-8_8</li>
<li>Choi, S. P. M., Lam, S. S., Li, K. C., &amp; Wong, B. T. M. (2018). Learning analytics at low cost: At-risk student prediction with clicker data and systematic proactive interventions. Educational Technology and Society, 21(2), 273–290.</li>
<li>Clow, D. (2013). Teaching in Higher Education An overview of learning analytics. Teaching in Higher Education, 18(6), 683–695. https://doi.org/10.1080/13562517.2013.827653 de Barba, P. G., Kennedy, G. E., &amp; Ainley, M. D. (2016). The role of students’ motivation and participation in predicting performance in a MOOC. Journal of - Computer Assisted Learning, 32(3), 218–231. https://doi.org/10.1111/jcal.12130</li>
<li>Ellis, R. A., Han, F., &amp; Pardo, A. (2017). Improving Learning Analytics – Combining Observational and Self-Report Data on Student Learning Improving Learning - Analytics – Combining Observational and Self-Report Data on Student Learning. Educational Technology &amp; Society, 20(3), 158–169. https://doi.org/10.2307/26196127</li>
<li>Ellis, R. A., Han, F., Pardo, A., Ellis, R. A., Han, F., &amp; Pardo, A. (2017). Improving Learning Analytics – Combining Observational and Self-Report Data on Student Learning Improving Learning Analytics – Combining Observational and Self-Report Data on Student Learning. Educational Technology &amp; Society, 20(3), 158–169.</li>
<li>Ferguson, R. (2012). Learning analytics: drivers, developments and challenges. International Journal of Technology Enhanced Learning, 4(5/6), 304. https://doi.org/10.1504/IJTEL.2012.051816</li>
<li>Gašević, D., Dawson, S., Rogers, T., &amp; Gasevic, D. (2016). Learning analytics should not promote one size fits all: The effects of instructional conditions in predicting academic success. Internet and Higher Education, 28, 68–84. https://doi.org/10.1016/j.iheduc.2015.10.002</li>
<li>Gašević, D., Dawson, S., &amp; Siemens, G. (2015). Let ’ s not forget : Learning analytics are about learning. TechTrends, 59(1), 64–71. https://doi.org/10.1007/s11528-014-0822-x</li>
<li>Goldstein, P. J., &amp; Katz, R. N. (2005). Academic Analytics : The Uses Of Management Information And Technology In Higher Education. EDUCAUSE Quarterly, 8(December), 113. https://doi.org/10.1080/17439880802097659</li>
<li>Greller, W., &amp; Drachsler, H. (2012). Translating Learning into Numbers: A Generic Framework for Learning Analytics Author contact details: Educational Technology &amp; Society, 15(3), 42 – 57. https://doi.org/http://hdl.handle.net/1820/4506 -Hart, S. A., &amp; Ganley, C. M. (2017). Individual differences related to college students’ course performance in Calculus II. Journal of Learning Analytics, 4(2), 129–153.</li>
<li>Howard, E., Meehan, M., &amp; Parnell, A. (2018). Contrasting prediction methods for early warning systems at undergraduate level. Internet and Higher Education, 37(January), 66–75. https://doi.org/10.1016/j.iheduc.2018.02.001</li>
<li>Jo, I.-H., Kim, D., &amp; Yoon, M. (2015). Constructing proxy variable to measure adult learners’ time management strategies in LMS. Journal of Education Techonology &amp; Society, 18(3), 214–225.</li>
<li>Junco, R., &amp; Clem, C. (2015). Predicting course outcomes with digital textbook usage data. Internet and Higher Education, 27, 54–63. https://doi.org/10.1016/j.iheduc.2015.06.001</li>
<li>Lang, C. (2017). Handbook of Learning Analytics. https://doi.org/10.18608/hla17 -Marbouti, F., Diefes-Dux, H. A., &amp; Madhavan, K. (2016). Models for early prediction of at-risk students in a course using standards-based grading. Computers and Education, 103, 1–15. https://doi.org/10.1016/j.compedu.2016.09.005</li>
<li>McInerney, D. M. (2005). Educational psychology - Theory, research, and teaching: A 25-year retrospective. Educational Psychology, 25(6), 585–599. https://doi.org/10.1080/01443410500344670</li>
<li>Miller, R. B., Greene, B. a., Montalvo, G. P., Ravindran, B., &amp; Nichols, J. D. (1996). Engagement in Academic Work: The Role of Learning Goals , Future Consequences , Pleasing Others ,. Contemporary Educational Psychology, 21(4), 388–422. https://doi.org/10.1006/ceps.1996.0028</li>
<li>Papamitsiou, Z., &amp; Economides, A. A. (2016). International Forum of Educational Technology &amp; Society Learning Analytics and Educational Data Mining in Practice: A Systematic Literature Review of Empirical Evidence Linked references are available on JSTOR for this article: Learning Analytics and Ed, 17(4).</li>
<li>Pardo, A., Han, F., &amp; Ellis, R. A. (2017). Combining University student self-regulated learning indicators and engagement with online learning events to Predict Academic Performance. IEEE Transactions on Learning Technologies, 10(1), 82–92. https://doi.org/10.1109/TLT.2016.2639508</li>
<li>Rojas Castro, P. (2017). Learning Analytics. Una Revisión de la Literatura. Educación Y Educadores, 20(1), 106–128. https://doi.org/10.5294/edu.2017.20.1.6</li>
<li>Romero, C., &amp; Ventura, S. (2010). Educational data mining: A review of the state of the art. IEEE Transactions on Systems, Man and Cybernetics Part C: Applications and Reviews. https://doi.org/10.1109/TSMCC.2010.2053532 -Saqr, M., Fors, U., &amp; Tedre, M. (2018). How the study of online collaborative learning can guide teachers and predict students’ performance in a medical course. BMC Medical Education, 18(1), 1–14. https://doi.org/10.1186/s12909-018-1126-1</li>
<li>Shaffer, D. R., &amp; Kipp, K. (2010). Developmental Psychology: Childhood and Adolescence.</li>
<li>Siemens, G. (2013). Learning Analytics: The Emergence of a Discipline. https://doi.org/10.1177/0002764213498851</li>
<li>Siemens, G., &amp; Long, P. (2011). Penetrating the Fog: Analytics in Learning and Education. EDUCAUSE Review, 46, 30–32. https://doi.org/10.1145/2330601.2330605</li>
<li>T Lu, O. H., Q Huang, A. Y., Huang, J. C., Q Lin, A. J., Ogata, H., H Yang, S. J., &amp; H Huang, J. C. (2018). Applying Learning Analytics for the Early Prediction of Students’ Academic Performance in Blended Learning. Source: Journal of Educational Technology &amp; Society Educational Technology &amp; Society, 21(212), 220–232. Retrieved from http://www.jstor.org/stable/26388400%0Ahttp://www.jstor.org/stable/26388400?seq=1&amp;cid=pdf-reference#references_tab_contents%0Ahttp://about.jstor.org/terms</li>
<li>Tyng, C. M., Amin, H. U., Saad, M. N. M., &amp; Malik, A. S. (2017). The influences of emotion on learning and memory. Frontiers in Psychology, 8(AUG). https://doi.org/10.3389/fpsyg.2017.01454</li>
<li>Wang, A. Y., &amp; Newlin, M. H. (2002). Predictors of we-based performance: the role olf self-effecacy and reasons for taking an on-line class. Computers in Human Behavior Journal, 18, 151–163.</li>
<li>You, J. W. (2016). Identifying significant indicators using LMS data to predict course achievement in online learning. Internet and Higher Education, 29, 23–30. https://doi.org/10.1016/j.iheduc.2015.11.003</li>
<li>Zacharis, N. Z. (2015). A multivariate approach to predicting student outcomes in web-enabled blended learning courses. Internet and Higher Education, 27, 44–53. https://doi.org/10.1016/j.iheduc.2015.05.002</li>
</ul>
</section>
</section>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>Under Construction</p>
</div>
</div>
</div>



<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>